# Generated by Django 3.1.1 on 2020-09-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20200925_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='image',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='url',
            new_name='refer_link',
        ),
    ]
