# Generated by Django 3.1.1 on 2020-09-25 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skills',
        ),
    ]
